### ISSUE TITLE
Publish source code

### ISSUE THREAD

**Issue by TWiStErRob** [TWiStErRob/net.twisterrob.colorfilters#16]
- [x] Create issue in target repo (#16)
- [x] Link it here (https://github.com/TWiStErRob/TWiStErRob-env/issues/8)
- [x] Clean up local copy
- [x] Use svn2git
- [x] Optional: Build CI
- [x] Delete from SVN (Last SVN commit: https://github.com/TWiStErRob/net.twisterrob.colorfilters/commit/55789ed2e63a08586a743f0ca71c7c94da4234b1, removed in r3334)
- [x] Replace p:\projects\workspace\x (.svn) with p:\project\workspace\repo.name.x (.git)
- [x] recreate/tag existing releases on GH (#28)

**Comment by TWiStErRob** [comment]
Last SVN commit: https://github.com/TWiStErRob/net.twisterrob.colorfilters/commit/55789ed2e63a08586a743f0ca71c7c94da4234b1
